title: PyTennessee 2020
email: organizers@pytennessee.org

baseurl: ""
url: "https://2020.pytennessee.org"
twitter_username: pytennessee

timezone: America/Chicago

permalink: pretty

collections:
  sponsors:
    output: false
  talks:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - pytn-2020.iml
  - README.md
  - scripts
  - .idea

visible:
  sponsors: true
  speaking: false
  speakers: true
  schedule: true
  game-night: false
